# Site settings
title: Personal Webpage
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Sean McDonough

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/sean-m-mcdonough/
  - title: instagram
    url: https://www.instagram.com/sfx600/
    title: resume
    url: https://i.imgur.com/OM80KY6.png
  - title: github
    url: https://github.com/seanmmcd

# Build settings
markdown: kramdown
permalink: pretty
