# Site settings
title:
email: smcdonough@umassd.edu
description: "This is a personal website, designed to host a portfolio and various personal contact information."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Sean McDonough

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: resume
    url: https://i.imgur.com/OM80KY6.png
  - title: linkedin
    url: https://www.linkedin.com/in/sean-m-mcdonough/
  - title: instagram
    url: https://www.instagram.com/sfx600/
  - title: github
    url: https://github.com/seanmmcd

# Build settings
markdown: kramdown
permalink: pretty
